### ISSUE TITLE
Error: The type 'ErrorDetail' exists in both 'Microsoft.Graph.Beta' and 'Microsoft.Graph.Core'

### ISSUE THREAD

**Issue by zekieshevked** [microsoftgraph/msgraph-beta-sdk-dotnet#144]
The following error occurs for Microsoft.Graph.Beta but did not occur for Microsoft.Graph:

The type 'ErrorDetail' exists in both 'Microsoft.Graph.Beta, Version=0.23.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.Graph.Core, Version=1.21.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	

Steps to reproduce:

1. Create C# Console Application
2. Install Microsoft.Graph.Beta nuget package
3. Add using Microsoft.Graph;
4. Type the following in Program.Main

    new ErrorDetail();
 
[AB#7136](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7136)

**Comment by MIchaelMainer** [comment]
Looks like the following was introduced:

      <ComplexType Name="errorDetail">
        <Property Name="errorCode" Type="Edm.String" />
        <Property Name="message" Type="Edm.String" />
        <Property Name="details" Type="Collection(graph.innerErrorDetail)" />
      </ComplexType>

We will need to update Microsoft.Graph.Core to be in the Microsoft.Graph.Core namespace. This should be in the 2.0.0 moment. 

ErrorDetails almost matches OData spec, but uses errorCode instead of code.
http://docs.oasis-open.org/odata/odata/v4.01/csprd05/part1-protocol/odata-v4.01-csprd05-part1-protocol.html#_Toc14172757

In the meantime, you can use the `extern alias` to differentiate classes coming from the core library.

Note to self: let's use metadata to filter this errorDetail out for now as mitigation.

**Comment by maisarissi** [comment]
Hi @zekieshevked 

The "ErrorDetail" has been renamed to ["PublicErrorDetail"](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Generated/model/PublicErrorDetail.cs).
