### ISSUE TITLE
List Chat Messages returns Bad Request

### ISSUE THREAD

**Issue by MaxiPigna** [microsoftgraph/msgraph-beta-sdk-dotnet#151]
When I call the Graph API to retrieve the list of chat messages, I get the first page of messages, but when I ask for the next page I get a Bad Request error.

![image](https://user-images.githubusercontent.com/33937977/91743949-f713c800-ebb8-11ea-97eb-75b227f748bd.png)

I highlighted in red the instruction where I get the Exception. 
More details:
```
Code: BadRequest
Message: Bad Request
Inner error:
    AdditionalData:
    date: 2020-08-31T16:31:59
    request-id: c917506e-6493-40ae-a725-f32832cf4f50
ClientRequestId: c917506e-6493-40ae-a725-f32832cf4f50
```

I am using the nuget package Microsoft.Graph.Beta **0.25.0-preview**. 
[AB#7140](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7140)

**Comment by MIchaelMainer** [comment]
I note a couple of things:
* The initial messages.NextPageRequest is assumed to be not null. We need to update the assumption because the the initial GetAsync request may result in a page that contains all of the chat messages, and therefore won't instantiate a NextPageRequest. Check NextPageRequest before trying to get another page.
* message.Count can be greater than 0 while request.NextPageRequest is null.

**Comment by MIchaelMainer** [comment]
After further investigation, the nextlink has erroneously encoded == characters at the end.

$skiptoken={shortened}MDB8MTU5ODg5MDkzMzE3NA%3d%3d

**Comment by andrueastman** [comment]
Closing this for now as this is not reproducible in the latest version of the SDK version 4 and 5.
