### ISSUE TITLE
IBookingAppointmentRequest.UpdateAsync() has wrong return type

### ISSUE THREAD

**Issue by navzam** [microsoftgraph/msgraph-beta-sdk-dotnet#183]
I'm using the following code to update a Bookings appointment:
```
var bookingAppointment = new BookingAppointment
{
    StaffMemberIds = new List<string> { staffMemberId },
};
...
var result = await graphServiceClient.BookingBusinesses[businessId].Appointments[bookingId]
    .Request()
    .WithUserAssertion(new UserAssertion(token))
    .UpdateAsync(bookingAppointment);
```
The return type of `UpdateAsync` is `Task<BookingAppointment>`, but the result of the task (`result`) is always `null`, even when the call succeeds. The [docs for Update bookingappointment](https://docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&tabs=http) also says that the API response will be `204` with no response body:

> If successful, this method returns a 204, No Content response code. It does not return anything in the response body.

which makes me think that the SDK return type is incorrect.

**Comment by MIchaelMainer** [comment]
This is expected and by design.

You are correct that the SDK return type is incorrect. We generate the API signature based on metadata that in some cases is not specific enough to help us construct a contract compliant API signature.

For us, it would be useful to have a terms that specifies whether an can result in a return representation.
