### ISSUE TITLE
Authentication Methods

### ISSUE THREAD

**Issue by exuviae** [microsoftgraph/msgraph-beta-sdk-dotnet#199]
I load a user with the following code:

var locatedUser = graphClient.Users.Request()
.Filter($"otherMails/any(id:id eq '{emailAddress}') or userPrincipalName eq '{emailAddress}' or mail eq '{emailAddress}'")
.GetAsync()
.Result;

when looking at locatedUser[0].Authentication it is always null. I can load with Query or with Id, and the result is the same. Is there something i am missing related to getting the authentication methods?

Complete example:

IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
.Create(clientId)
.WithTenantId(tenantId)
.WithClientSecret(clientSecret)
.Build();

ClientCredentialProvider authProvider = new ClientCredentialProvider(confidentialClientApplication);
GraphServiceClient graphClient = new GraphServiceClient(authProvider);

var locatedUser = graphClient.Users.Request()
.Filter($"otherMails/any(id:id eq '{emailAddress}') or userPrincipalName eq '{emailAddress}' or mail eq '{emailAddress}'")
.GetAsync()
.Result;
foreach (var user in locatedUser)
{
if (user.Authentication != null)
{
foreach (var authenticationPhoneMethod in user.Authentication.PhoneMethods)
{
Console.WriteLine(authenticationPhoneMethod.PhoneNumber);
}
}
else
Console.WriteLine("Authentication methods does not exist");
} 
[AB#7148](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7148)

**Comment by MIchaelMainer** [comment]
You'll need to access that authentication methods like this:

`client.Users[userId].Authentication.Methods.Request().GetAsync()`

This appears to only be available on the beta endpoint.

**Comment by andrueastman** [comment]
@exuviae Any chance the information provided by @MIchaelMainer was helpful?

**Comment by exuviae** [comment]
This allows you to get the basic authentication methods.  How do you add/ remove a phone number used for MFA.
Chris


Sent from Yahoo Mail for iPhone


On Friday, January 15, 2021, 12:56 AM, Eastman <notifications@github.com> wrote:




@exuviae Any chance the information provided by @MIchaelMainer was helpful?

**Comment by maisarissi** [comment]
Hi @exuviae .

Looking at the API docs page, it seems like it's possible to [list up to three phones usable for authentication](https://docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-beta&tabs=csharp).
Also, you can [add](https://docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-beta&tabs=csharp#examples) or [remove](https://docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-beta&tabs=csharp#examples) a user's phone authentication by following the code snippets in the docs.

Since the feature is on available on beta endpoint, this is only supported by .NET Beta SDK.

Hope this can help.
