### ISSUE TITLE
Update printer capabilities and defaults

### ISSUE THREAD

**Issue by mwetzko** [microsoftgraph/msgraph-beta-sdk-dotnet#213]
The following call:

`await new GraphServiceClient(new ClientCredentialProvider(app)).Print.Printers["<printerId>"].Request().UpdateAsync(new Printer(){/*this to update*/});`

throws the follwoing exception

`"The token does not have one or more required security scopes."`

I was wondering what is going on. Because the docs say, only "https://graph.microsoft.com/.default" is the scope to go with, which is used by default by the ClientCredentialProvider constructor.
Using a specific scope like "Printer.ReadWrite.All" or even "https://graph.microsoft.com/Printer.ReadWrite.All" will throw the following exception:

`"AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope Printer.ReadWrite.All is not valid."`

Somebody any ideas? 
[AB#7778](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7778)

**Comment by andrueastman** [comment]
@mwetzko Any chance you share a code snippet of how you are setting the scopes?

Also, According to [this](https://docs.microsoft.com/en-us/graph/api/printer-update?view=graph-rest-beta&tabs=http#permissions) you might also need the `Printer.FullControl.All` permission.

**Comment by mwetzko** [comment]
Of course! [Program.cs](https://github.com/mwetzko/test/blob/master/dotnet/microsoft%20graph/Update%20Printer/Update%20Printer/Program.cs)

Output of this:
```
...

Testing [https://graph.microsoft.com/.default]...
=================================================
Test Scopes returned by API:
----------------------------
https://graph.microsoft.com/.default

Update Printer:
----------------------------
Code: 403
Message: The token does not have one or more required security scopes.



Testing [Printer.ReadWrite.All]...
==================================
Test Scopes returned by API:
----------------------------
AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope Printer.ReadWrite.All is not valid.

Update Printer:
----------------------------
Code: generalException
Message: An error occurred sending the request.



Testing [https://graph.microsoft.com/Printer.ReadWrite.All]...
==============================================================
Test Scopes returned by API:
----------------------------
AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://graph.microsoft.com/Printer.ReadWrite.All is not valid.

Update Printer:
----------------------------
Code: generalException
Message: An error occurred sending the request.



Testing [Printer.FullControl.All]...
====================================
Test Scopes returned by API:
----------------------------
AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope Printer.FullControl.All is not valid.

Update Printer:
----------------------------
Code: generalException
Message: An error occurred sending the request.



Testing [https://graph.microsoft.com/Printer.FullControl.All]...
================================================================
Test Scopes returned by API:
----------------------------
AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://graph.microsoft.com/Printer.FullControl.All is not valid.

Update Printer:
----------------------------
Code: generalException
Message: An error occurred sending the request.


```

I tried any permission possible. Even https://print.print.microsoft.com/.default. But this ends up in "Invalid audience" exceptions.

According to the docs, Printer.ReadWrite.All should be enough.
[https://docs.microsoft.com/en-us/graph/api/printer-update](https://docs.microsoft.com/en-us/graph/api/printer-update)

On API Permission basis, everything is green and has admin consent.
![Permissions](https://user-images.githubusercontent.com/49561427/105836686-d5830500-5fcd-11eb-9637-2767dd452553.png)

**Comment by andrueastman** [comment]
@mwetzko 
Since you are using application permissions with the ClientCredentialProvider, the correct way would be to just use the  `https://graph.microsoft.com/.default` scope and then enable the relevant application permissions on the azure portal. 

However, it seems you have enabled the right scopes according to the documentation. Let me try raise to raise this with the relevant team and feedback any response incase there is something amiss.

**Comment by andrueastman** [comment]
@mwetzko 
After taking a second look at the code, I believe the issue the issue is with how you are you setting up the confidential client [here](https://github.com/mwetzko/test/blob/a6dae6c33cd9084c88147e3b2c4c157cf6314a10/dotnet/microsoft%20graph/Update%20Printer/Update%20Printer/Program.cs#L27)

The second parameter should not be `organizations` but your `tenant-id`.(After I changed this, it worked out for me).

You can find it right below the client id in the azure portal as shown in the figure below.
![image](https://user-images.githubusercontent.com/6464005/106036411-60efb980-60e6-11eb-9323-3c653d5c8845.png)

Also note that according to the documentation [here](https://docs.microsoft.com/en-us/graph/api/printer-update?view=graph-rest-beta&tabs=http#permissions), only printers that don't have a physical device can be updated using application permissions. If this is the case you might have to consider switching to Delegated Permissions.

**Comment by mwetzko** [comment]
@andrueastman fantastic! It is working with the tenant id of the registered application.

Yes, the printer end is virtual and I already tested updating some capabilities with application permission. So thats working also.

Thank you very much for your help!

**Comment by andrueastman** [comment]
No worries @mwetzko! Happy to help 😄
