### ISSUE TITLE
@odata.type property is missing on objects in some MS Graph endpoints

### ISSUE THREAD

**Issue by Yomodo** [microsoftgraph/msgraph-beta-sdk-dotnet#307]
I've noticed through the SDK and Graph Explorer (https://developer.microsoft.com/en-us/graph/graph-explorer)
that objects retrieved from the following MS Graph Beta endpoint suddenly don't have the @odata.type property anymore:

https://graph.microsoft.com/beta/Groups/
https://graph.microsoft.com/beta/devicemanagement/DeviceManagementScripts
https://graph.microsoft.com/beta/devicemanagement/GroupPolicyConfigurations
https://graph.microsoft.com/beta/devicemanagement/Intents
https://graph.microsoft.com/beta/devicemanagement/TermsAndConditions

Other MS Graph Beta endpoints that we use don't seem to suffer from this:
https://graph.microsoft.com/beta/devicemanagement/DeviceCompliancePolicies
https://graph.microsoft.com/beta/devicemanagement/DeviceEnrollmentConfigurations
https://graph.microsoft.com/beta/devicemanagement/Templates
https://graph.microsoft.com/beta/devicemanagement/WindowsAutopilotDeploymentProfiles

The JSON of this MS Graph Beta endpoint does not look right:
https://graph.microsoft.com/beta/devicemanagement/DeviceConfigurations
![image](https://user-images.githubusercontent.com/10358198/121029637-0d366080-c7a9-11eb-95c4-ab85dd58405b.png)

**Comment by andrueastman** [comment]
@Yomodo Thanks for raising this. 
It looks like this is a change in API and this repo is intended for issues only related with the .NET beta client library. 

The best place to follow it up would be to open a question at the link below in the relevant section depending on the API you are trying to call. The relevant workload team(e.g. groups) will provide us with a better answer for this. 

https://docs.microsoft.com/en-us/answers/products/m365#microsoft-graph

It would be great if you posted the link to the question here as well so that people searching in the future may benefit from the answer as well.

**Comment by Yomodo** [comment]
I posted the same question at [docs.microsoft.com](https://docs.microsoft.com/en-us/answers/questions/476302/-38.html)
