### ISSUE TITLE
GraphServiceClient regenerates a new token for every API call?

### ISSUE THREAD

**Issue by RafaAyadi** [microsoftgraph/msgraph-beta-sdk-dotnet#347]
I am using a GraphServiceClient that is generated with a Username/Password on behalf of a user, just like described in this doc: https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS#usernamepassword-provider

Whenever I call any API using my GraphServiceClient, it reauthenticates and generates a new token. This is causing this error to appear: AADSTS50196: The server terminated an operation because it encountered a client request loop?

Is there any way to prevent this and get the GraphServiceClient to reuse the same token and only regenerate it if it expires?

**Comment by andrueastman** [comment]
Hey @RafaAyadi,

Thanks for raising this.

I believe this is related to https://github.com/Azure/azure-sdk-for-net/issues/23324.

If you are willing you can try out Azure.Identity version 1.5.0-beta.4 which has the fix in place. Otherwise, I believe the upcoming stable version 1.5.0 should have this fixed.
