### ISSUE TITLE
Authentication methods not available at Graph API and UI 

### ISSUE THREAD

**Issue by aristotelis79** [microsoftgraph/msgraph-beta-sdk-dotnet#355]
I have an issue with authentication methods on a B2C tenant and more specific with mobile.

While there is an entry on the mobile at the current Azure Portal UI of authentication methods, this entry is not available from GraphAPI (v.1 or beta) (I have available all the right permissions) and the new authentication experience and is not available to take.

![old](https://user-images.githubusercontent.com/9366110/137619704-e6d9db4a-aa75-463f-8e15-de1c8c04a457.png)

![new](https://user-images.githubusercontent.com/9366110/137619693-e40ef02b-80d1-47e9-9f18-c5f42649a06f.png)

Now the only way to have it available at GraphAPI (and new experience ) is to enable manually the indicator ( shown in the screenshot) to use the phone as a sign-in method which I do not want anyway because I want it only as MFA.

The more strange are although is beside I tried to turn it on the phone sign in the issue persists.

Also If I create the entry from Graph API also is available as it should be.

Can anyone know if I miss a configuration or is a bug?

**Comment by andrueastman** [comment]
Hey @aristotelis79,

Thanks for raising this issue.

As this repository is ideally meant for SDK related issues/queries, please raise the same query at the link below and an API owner will give feedback on what needs to be done. It would be great if you could post the link to the question in this issue so that anyone in future may be able to find it as well.

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-authentication.html

Closing this for now and will reopen if anything related to the SDK is raised.
