### ISSUE TITLE
eDiscovery custodian for a given email always has the same ID

### ISSUE THREAD

**Issue by rubens-farias** [microsoftgraph/msgraph-beta-sdk-dotnet#358]
Microsoft.Graph.Beta 4.17.0-preview.

Consider this code for create a eDiscovery custodian within a case:

```
return custodians.FirstOrDefault(c =>
    String.Equals(c.Email, email,
        StringComparison.InvariantCultureIgnoreCase)) ?? await client
    .Compliance
    .Ediscovery
    .Cases[caseId.ToString()]
    .Custodians
    .Request()
    .AddAsync(new Microsoft.Graph.Ediscovery.Custodian
    {
        Email = email,
        ApplyHoldToSources = false
    });
```

eDiscovery returns a specific **custodian ID** that happens to be the the **AAD User ID** for that email address.

If we create the same custodian _in a different case_, we get the _same ID_ (and this seems odd).
If we try to add the same custodian twice in the same case, we receive an error, as expected.

In the current eDiscovery API design, custodians are always bound to a case and cannot be globally searched without looping through all cases.

Is this the planned behavior, or could it be a misplaced value in the API return?

**Comment by bwingate01** [comment]
@mahage-msft Hi Marshall, this is Brian Wingate from the Lighthouse team.   We were expecting that the Custodian, like the AED Case, would have a distinct object created, with it's own AED GUID. In other words, it doesn't seem like Custodian is a first-class-citizen, so to speak, in the AeD data model.    It's not an issue, just unexpected.

**Comment by mahage-msft** [comment]
IT does have a distinct object created, but it's within the context of the case. For any GUID, there's never a guarantee of uniqueness, except from within a case. In the case of the custodian, it's very apparent because we use the AAD ID of the user. This was intentional so there's a quick way to look up the user in AAD if needed. Still not clear why this is a problem.

**Comment by bwingate01** [comment]
Thanks Marshal.  I believe we already indicated it was not an issue, just unexpected.  Appreciate the rationale for quick look up for user in AAD.  And understood re: uniqueness within a case.  Just seemed discordant with the approach for, say, sitesource as a Custodial or even NonCustodial source.  There, an AeD object is created for the site, with it's own AeD ID, even though the site itself bears a unique id in the tenant.   

Thanks for the prompt reply!!

**Comment by johnholliday** [comment]
@mahage-msft If the uniqueness of custodian identifiers is not guaranteed beyond the scope of the associated case, then the case identifier should be included in the metadata stored with each custodian.  Currently, the custodian data structure does not include the associated case identifier. This causes the custodian object to be disassociated from the case to which it belongs, resulting in unnecessary complexity in client applications, which are then forced to maintain the association.  

As an example, consider a client application that wants to store custodian objects in a distributed cache to reduce roundtrips between requests. Since custodian identifiers are not globally unique, the application would need to use a composite key by combining the case identifier with the custodian identifier and would likely also need to cache the case as well as the custodian.

**Comment by mahage-msft** [comment]
@johnholliday, I don't think uniqueness or even non-uniqueness would help in this case. The only way to get a handle to a custodian is to have the case. It's by design that we do not return the associated case with each call because it would be redundant since you are required to provide the case Id when you make the call to add or get the custodian.

@bwingate01 - Actually, site sources do have the same behavior. The ID for the site source is the [graph] ID of the site. If you have sufficient permissions, you can use this ID with the /sites API. I'm looking closer at the IDs provided for NCDS, those are actually the internal NCDS Id, it seems the site source isn't properly exposed.
