### ISSUE TITLE
Windows10CompliancePolicy.ScheduledActionsForRule should allow easy construction

### ISSUE THREAD

**Issue by zachcwillson** [microsoftgraph/msgraph-beta-sdk-dotnet#392]
If you want to instantiate the `ScheduledActionsForRule` for a `Windows10CompliancePolicy` object, you have to follow the following steps:
```
DeviceCompliancePolicyScheduledActionsForRuleCollectionPage newPage = new();
var actions = new List<DeviceComplianceScheduledActionForRule>(); // Get list from somewhere
foreach (var action in actions)
{
    newPage.Add(action);
}
Windows10CompliancePolicy policy = new()
{
    ScheduledActionsForRule = newPage
};
```
This is because `ScheduledActionsForRule` is type `IDeviceCompliancePolicyScheduledActionsForRuleCollectionPage` and `DeviceCompliancePolicyScheduledActionsForRuleCollectionPage` does not expose a constructor to pass in the actions as a list.

`DeviceCompliancePolicyScheduledActionsForRuleCollectionPage` inherits from `CollectionPage<DeviceComplianceScheduledActionForRule>`, so `DeviceCompliancePolicyScheduledActionsForRuleCollectionPage` could expose a constructor that calls `base(actions)` that would call `public CollectionPage(IList<T> currentPage)`.

Enabling this would change the above codeblock to:
```
var actions = new List<DeviceComplianceScheduledActionForRule>();
Windows10CompliancePolicy policy = new()
{
    ScheduledActionsForRule = new DeviceCompliancePolicyScheduledActionsForRuleCollectionPage(actions)
};
```

**Comment by zengin** [comment]
This actually makes a lot of sense. `List` -> `CollectionPage` conversion should be supported without requiring clients to iterate over the list to assign elements one by one, given that the underlying data structure is a `List` anyways.

The only concern I have is the "pass by reference" behavior, so the client will have a control over the internal `List` of the `CollectionPage`. But that is already possible with generic `CollectionPage<T>` constructor, because it is implemented without a copy:

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/6ec55dcc43b884cec3d61aeb3ceb69fe27852157/src/Microsoft.Graph.Core/Models/CollectionPage.cs#L27-L31

Regardless of how the reference/copy behavior is going to be defined, we can consider exposing a constructor with an argument of type `List` to simplify client logic.

@baywet, what does this look like in SDKs generated by kiota?

**Comment by andrueastman** [comment]
@zengin Collection properties are now represented as instances of type `List` in the next version. This means that this should be resolved in Kiota

**Comment by zachcwillson** [comment]
Hey @andrueastman and @zengin, thanks for the update. What is Kiota and what is the timeframe for us to consume it?

**Comment by andrueastman** [comment]
Hey @zachcwillson,

We are working on replacing the current SDK generator with a new generator called [Kiota](https://github.com/microsoft/kiota) which will offer the benefits of resolving several issues we have with the current generator. We're aiming to come up with a preview SDK to get feedback in the coming weeks.

**Comment by andrueastman** [comment]
This is now resolved in the latest V5 previews. The property is represented as an instance of `List` as shown in the link below.

https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/3872aa5dba83344c4597dbefbea577678e617479/src/Microsoft.Graph/Generated/Models/DeviceCompliancePolicy.cs#L55
