### ISSUE TITLE
Gaps and issues with AppRoleAssignments implementation

### ISSUE THREAD

**Issue by kalyankrishna1** [microsoftgraph/msgraph-beta-sdk-dotnet#40]
Hi, I am doing some validation work on App roles and AppRoleAssignments, and found out that the SDK hasn't implemented this as per the spec as outlined by @psignoret [here](https://stackoverflow.com/questions/45203126/how-to-use-approleassignment-in-graph-api)

I am providing some sample code with comments below for reference.

          ```

  // Supported and works
            var a = await graphServiceClient.Me.AppRoleAssignments.Request().GetAsync();

            // Not navigable today, thus no way to retrieve the assignments for a service principal or group
            var b = await graphServiceClient.Groups.AppRoleAssignments.Request().GetAsync();
            var c = await graphServiceClient.ServicePrincipals.AppRoleAssignments.Request().GetAsync();

            // this throws the unsupported query error
            var d = await graphServiceClient.AppRoleAssignments.Request().GetAsync()
```

**Comment by darrelmiller** [comment]
The navigation properties for AppRoleAssignments on Group and ServicePrincipal were only generated on Sept 19th.  The last beta package we released did not include those changes.  We have been delayed in getting a beta update out due to issues with the metadata.  Those issues were resolved on Wednesday.  I expect an update to make it out on Monday or Tuesday /cc @MIchaelMainer to confirm.

The graphServiceClient.AppRoleAssignments is not a valid entity set as all the other navigation properties are containment navigation properties (i.e. ContainsTarget=true).  I do not believe OData allows an entityset in the entityContainer and containment navigation properties.   Either the entitySet owns the entities and the navigation properties refer to collections that are just references, or the navigation properties own all the entities.  

> An entity cannot be referenced by more than one containment relationship and cannot both belong to an entity set declared within the entity container and be referenced by a containment relationship.

https://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/csprd06/odata-csdl-xml-v4.01-csprd06.html#sec_ContainmentNavigationProperty

I believe the appRoleAssignments entityset in the entityContainer should be removed from the metadata.  /cc @dkershaw10
