### ISSUE TITLE
Search API: EntityType.DriveItem enum translates to "driveItem" instead of "microsoft.graph.driveItem"

### ISSUE THREAD

**Issue by vman** [microsoftgraph/msgraph-beta-sdk-dotnet#43]
Package: **Microsoft.Graph.Beta 0.9.0-preview**

Sample code:
```
var requests = new List<SearchRequestObject>()
                            {
                                new SearchRequestObject
                                {
                                    EntityTypes = new List<EntityType>()
                                    {
                                        EntityType.DriveItem
                                    },
                                    Query = new SearchQuery
                                    {
                                        Query_string = new SearchQueryString
                                        {
                                            Query = "contoso"
                                        },
                                    },
                                    From = 0,
                                    Size = 25
                                }
                            };

            var result = await graphClient.Search.Query(requests).Request().PostAsync();
```
This translates to the following REST call:

![image](https://user-images.githubusercontent.com/173794/70067023-93d31600-15e5-11ea-8701-66677c34d218.png)

Which returns an error:

_Could not convert the provided enum type: driveItem_

Ideally, it should translate to `microsoft.graph.driveItem` as mentioned in the docs: https://docs.microsoft.com/en-us/graph/search-concept-files#example

This is probably the case for all other entity types as well.

**Comment by butchersoft1** [comment]
have you got an ETA on this fix?  happens for all EntityTypes - microsoft.graph.message for example

{"requests":[{"entityTypes":["microsoft.graph.message"],"query":{"query_string":{"query":"dams","@odata.type":"microsoft.graph.searchQueryString"},"@odata.type":"microsoft.graph.searchQuery"},"from":0,"size":25,"@odata.type":"microsoft.graph.searchRequest"}]}

**Comment by nadjibus** [comment]
This bug is a total show stopper. Nothing works in Search endpoint...
Quick workaround:

```
private class FixedSearchRequestObject : SearchRequestObject
{
    [JsonProperty("entityTypes")]
    public string[] EntityTypesString { get; set; }
    public bool ShouldSerializeEntityTypes() => false;
}
```

Usage:
```
var request = GraphClient.Search.Query(new[] 
    { 
        new FixedSearchRequestObject
        {
            EntityTypesString = new[] { "microsoft.graph.message" },
            Query = new SearchQuery { Query_string = new SearchQueryString { Query = $"to:{fromToEmail}" } }
        } 
    }).Request();

var results = await request.PostAsync();
```

**Comment by darrelmiller** [comment]
Hey @nmoreau I believe this is going to need to be fixed in the service.  The docs show this example:

```
      "entityTypes": [
        "microsoft.graph.driveItem"
      ],
```
but that is not a valid enum value.  In the metadata the enum is defined like this,

![image](https://user-images.githubusercontent.com/447694/71751003-24e91700-2e48-11ea-9bb4-f543161a6986.png)

and hence that is how the enum in the SDK is defined.  Either the `microsoft.graph.` prefix needs to be dropped or it needs to be changed to use a language compatible character like `microsoft_graph_driveitem`.  The problem with dropping the prefix is we may run into clashes in the future when add support for multiple namespaces in Microsoft Graph types

**Comment by nmoreau** [comment]
Thanks Darrel for the heads up.
Since we have published the docs and sample with this definition of the enum, I’d like to stick with it.
Some clients have already taken a dependency on this.
What we may be able to do is to support the non prefixed version as well so that the SDK call can work.
Adding @Bhumik Thakkar<mailto:bhthakka@microsoft.com> as well.

**Comment by darrelmiller** [comment]
Hey @nmoreau .  I just checked with the OData folk.  As per the OData specification a period is not allowed in the name of a enum member.  The periods will need to be removed from the name.  Fortunately the API is still in beta so this is the right time to make the change.

**Comment by nmoreau** [comment]
@darrelmiller  : This is tracked as this bug in our repo. We'll work on it.
Bug 1352705: Enums in request should be supported without "." prefix

**Comment by nmoreau** [comment]
This issue has been fixed.
The service is now accepting entityTypes without the prefix.
No change in the SDK is required.
Thank you for your patience.

   "entityTypes": [
        "driveItem"
      ],

**Comment by vman** [comment]
Hi @nmoreau just tested it and it works with the SDK. Thanks! Will close the issue now.
