### ISSUE TITLE
Support to apply sensitivity label to a Microsoft 365 group using app only token

### ISSUE THREAD

**Issue by matsla** [microsoftgraph/msgraph-beta-sdk-dotnet#515]
This seems to only be supported using delegated permission. When will this be supported using app only token?

https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&tabs=http

Request
You can obtain the ID of the label you want to apply to a Microsoft 365 group by using [List label](https://docs.microsoft.com/en-us/graph/api/informationprotectionpolicy-list-labels?view=graph-rest-beta). Then you can update the [assignedLabels](https://docs.microsoft.com/en-us/graph/api/resources/assignedlabel?view=graph-rest-beta) property of the group with the label ID.

Note: Use of this API to apply sensitivity labels to Microsoft 365 groups is only supported for **delegated permission** scenarios.

**Comment by andrueastman** [comment]
Closing this one for now as this is an API related request.

We've forwarded the request at the link below so that it may be followed up by the relevant API owners. 

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/support-to-apply-sensitivity-label-to-a-microsoft-365-group/idi-p/3685845#M1491
