### ISSUE TITLE
Multiple Filters Failing

### ISSUE THREAD

**Issue by shyamal890** [microsoftgraph/msgraph-beta-sdk-dotnet#614]
Example code is being executed on `graphClient.Users`

```
                var filter_query1 = $"(identities/any(id:id/issuer eq ' ' and id/issuerAssignedId eq '{email}'))";
                var filter_query2 = $"(mail eq '{email}')";
                var filter_query_final = filter_query1 + " or " + filter_query2;

                var result = await graphClient.Users.GetAsync(x =>
                {
                    x.QueryParameters.Filter = filter_query_final;
                });
```

And I am getting `Complex query on property identities is not supported.` error. 

SDK version - 5.19.0-preview

**Comment by andrueastman** [comment]
Thanks for raising this @shyamal890 

As this looks to be an issue with the API not supporting the filter on the `identities` property and not with the client library, any chance of you creating a feature request at the link below so that the API team may look into adding the support?
I would suggest posting back the link for the created issues so that others may find and upvote it as well. 

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

We'll close this one for now and re-open in the event of any SDK related issues.
