### ISSUE TITLE
ERROR: The audience claim value is invalid for current resource

### ISSUE THREAD

**Issue by mhagesfeld** [microsoftgraph/msgraph-beta-sdk-dotnet#64]
I am trying to use the following code, but am getting "Message: The audience claim value is invalid for current resource. Audience claim is 'https://graph.microsoft.com', request url is 'https://outlook.office.com/api/beta/Users..."

I get it on the provider.GetUploadChunkRequests(); call below:

AttachmentItem attachmentItem= new AttachmentItem
            { 
                Name = [Name],
                AttachmentType = AttachmentType.File,
Size = [Size]
            };

var session = graphClient.Users[USEREMAIL].Messages[MESSAGEID].Attachments.CreateUploadSession(attachmentItem).Request().PostAsync().Result;
            var stream = new MemoryStream(BYTEARRAY);
            var maxSizeChunk = DEFAULT_CHUNK_SIZE;
            var provider = new ChunkedUploadProvider(session, graphClient, stream, maxSizeChunk);
            var chunkRequests = provider.GetUploadChunkRequests();

(I am using the graphClient to send emails successfully, and have also used it to upload large files using the uploadSession method)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95441aec-d30e-394b-a816-25d1537bfe50
* Version Independent ID: 7f59d2e4-52fa-cd12-6817-13b2ee153b2d
* Content: [attachment: createUploadSession - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/attachment-createuploadsession?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/attachment-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/attachment-createuploadsession.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam** 
[AB#7155](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7155)

**Comment by matrad** [comment]
any news on this issue?

**Comment by askdesigners** [comment]
Also hitting this error, and no idea what to do...

**Comment by andrueastman** [comment]
This is caused by the fact that the client adds the Auth header by default when sending requests (doing the upload). According to the docs [here](https://docs.microsoft.com/en-us/graph/outlook-large-attachments?tabs=http#request-headers), the Auth header shouldn't be sent.  This could be worked around by creating a graphClient with a null `AuthenticationProvider` to do the upload for you.

The ChunkedUploadProvider has, however, been deprecated and the LargeFileUploadTask should be used instead and should work without issues. The link below shows how to use it. 

https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?view=graph-rest-1.0&tabs=csharp
