### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by DanLepageOrbit** [microsoftgraph/msgraph-beta-sdk-dotnet#717]
Hi we have been working with the beta since its release but have had some issue and was wondering if you could help point us in the right direction.

With graph calls, we create a teams meeting, add a bot to it, invite participants and listen to the start and end meeting activity handlers.

We have been testing Teams calls for some time now and we have noticed a random disruption in the call’s connection. This happens periodically, but it has been happening for a several months now..
 
Each morning a series of tests are performed and at random intervals, the call cannot connect. Sometimes its first call in the morning, sometimes its after a few tries. Typically, when a call fails to connect, it will work again after 15 – 20 minutes, but it can also be shorter or longer delays.
 
Could it be related to a hit per second blocker?
 
This issue has been consistently happening daily, but every other aspect has been on random intervals, any thought on what could be preventing the calls to be established. We have been looking hard on our end and trying to update the logs for a more accurate depiction of the error but have had no success yet.
 
Let us know if you can find anything or can provide any support.
 
Thanks,

**Comment by andrueastman** [comment]
Thanks for raising this @DanLepageOrbit 

As your question relates to API side functionality and this repo is mainly intended for SDK related issues, any chance you can post the same question at the link below so that the API owners may provide their insights? It would be great if you could post the link to the same here so that anyone who comes across it may also benefit from the info.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
