### ISSUE TITLE
EmployeeExperience.Communities.PostAsync no longer successfully creates Viva Communities

### ISSUE THREAD

**Issue by afowler1** [microsoftgraph/msgraph-beta-sdk-dotnet#808]
In the graph beta sdk version 5.60.0 the `EmployeeExperience.Communities.PostAsync` method was successfully creating Viva Engage Communities using [this code example](https://gist.github.com/timward60/fd5727e5561d67c02fff3d9e73555058). 
Now it does not (using the latest version 5.67.0). 

I am able to call the creation method successfully, and then I am able to call the `EmployeeExperience.EngagementAsyncOperations[operationId].GetAsync()` method successfully. It returns the LongRunningOperationStatus.Succeeded message but when I check Entra or the 365 portal, no group has been created. If I try to call `EmployeeExperience.Communities[communityId].GetAsync()`, I get a null response (I assume because the group never existed). 
 
 
This is an example response from the `EngagementAsyncOperations`method.
![image](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/assets/149447717/420dc0f6-a4e4-43a2-8f52-4079629806fd)

Trying to return the community after creation returns a null response.
![image](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/assets/149447717/1155a7e6-da3b-413f-85ed-c4640cd6ab24)

**Comment by andrueastman** [comment]
Thanks for raising this @afowler1 

Just to confirm, does this mean that if you downgrade the SDK to `5.60.0` the call works without issue?

**Comment by afowler1** [comment]
Hi @andrueastman, downgrading to `5.60.0` results in the same exact same issue.

**Comment by andrueastman** [comment]
Thanks for clarifying this. 

Given that this is a behavior change in the API, and we may not be the best placed to answer as this repo is mainly intended for SDK related issues, any chance you can post the question at the link below to get feedback from the API owners on whether this change of behavior is intended? It would be great if you could post a link to the created question so that anyone who comes across this may also find the information. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by afowler1** [comment]
@andrueastman, it turns out the issue was my fault. I was trying to set the group admin to a user from a different tenant than the one Graph was connected to. 
Maybe we could look adding a specific error if the group admin in `"owners@odata.bind"` is invalid?
